### ISSUE TITLE
[FIX] wandb logging type change  

### ISSUE THREAD

**Issue by lbong2** [boostcampaitech5/level2_objectdetection-cv-09#27]
## Background
- wandb에 업로드 되는 cfg 변수 타입 캐스팅
    
## Todo
- [x] wandb에 cfg정보가 업로드 되는지 확인  
- [x] 이미지 파일 로깅 추가
- [x] entity 파라미터 추가
